CREATE TABLE IF NOT EXISTS game (
    id INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE IF NOT EXISTS player_move (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    game_id INTEGER NOT NULL,
    piece CHAR NOT NULL,
    side VARCHAR NOT NULL,
    FOREIGN KEY (game_id) REFERENCES game(id)
);
